# Args: <cam_file> <obj_file> <output_dir>
{
  "version": 1,
  "setup": {
    "blender_install_path": "/Applications/Blender.app/Contents/MacOS",
    "blender_version": "blender-2.81-linux-glibc217-x86_64",
    "pip": [
      "h5py",
      "imageio",
      "scikit-image",
      "pypng==0.0.18",
      "scipy==1.2.2"
    ],
    "bop_toolkit_path": "/Users/louis/Desktop/DoctorProject/project/bop_toolkit"
  },
  "global": {
    "all": {
      "output_dir": "<args:1>",
      "sys_paths": ["/path/to/bop_toolkit"]
    },
  },
  "modules": [
    {
      "name": "main.Initializer",
      "config": {}
    },
    {
      "name": "loader.BopLoader",
      "config": {
        "bop_dataset_path": "<args:0>",
        "mm2m": True,
        "split": "test",
        "scene_id": "<args:2>",
        "model_type": "scaled"
      }
    },
    {
      "name": "lighting.LightSampler",
      "config": {
        "lights": [
        {
          "location": {
            "name": "sampler.Shell",
            "center": [0, -2.0, 0],
            "radius_min": 1,
            "radius_max": 4,
            "elevation_min": 40,
            "elevation_max": 89
          },
          "type": "POINT",
          "energy": 1000
        }, {
          "location": [0, 0, 0],
          "type": "POINT",
          "energy": 100
        }
      ]
      }
    },
    {
      "name": "renderer.RgbRenderer",
      "config": {
        "samples": 150
      }
    },
    {
      "name": "renderer.SegMapRenderer",
      "config": {
        "map_by": "instance"
      }
    }
  ]
}
